openapi: 3.0.3
info:
  title: User API
  description: >-
    Esto es una combinacion de varios esquemas que se encuentran referenciados y que se han generado a partir del script
    Aqui lo que se ha hecho es coger los esquemas que se encuentran referenciados y se han generado los ejemplos para cada uno de ellos
    "UserBase" -> Se genera una propiedad id dentro de ella un array de string ids con el ejemplo que se tiene a nivel de la propiedad ids.

    Esto ha sido un ejemplo para ver el comportamiento que se tiene con la anidacion de objetos y arrays.
  version: 1.0.0
paths:
  /user:
    get:
      summary: Retrieve user information
      responses:
        '200':
          description: User information retrieved successfully
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/UserBase'
                  - $ref: '#/components/schemas/UserStatus'
                  - $ref: '#/components/schemas/UserContact'
                  - $ref: '#/components/schemas/UserRoles'
              examples:
                GeneratedExample94D4:
                  $ref: '#/components/examples/GeneratedExample94D4'
components:
  schemas:
    UserBase:
      type: object
      properties:
        id:
          type: object
          properties:
            ids:
              type: array
              items:
                type: string
              example:
                - 12345
                - 23456
        name:
          type: string
          example: John Doe
    UserStatus:
      type: object
      properties:
        status:
          type: string
          example: active
        lastLogin:
          type: string
          format: date-time
          example: '2023-05-23T08:30:00Z'
    UserContact:
      type: object
      properties:
        email:
          type: string
          format: email
          example: johndoe@example.com
        phone:
          type: string
          example: '+1234567890'
    UserRoles:
      type: object
      properties:
        roles:
          type: array
          items:
            type: string
            example: admin
      example:
        roles:
          - admin
          - user
  examples:
    GeneratedExample94D4:
      summary: Example generated by script
      value:
        id:
          ids:
            - 12345
            - 23456
        name: John Doe
        status: active
        lastLogin: '2023-05-23T08:30:00Z'
        email: johndoe@example.com
        phone: '+1234567890'
        roles:
          - admin
          - user
