openapi: 3.0.3
info:
  title: Example API
  description: >-
    Esto es un ejemplo que nos puede llegar , puede ser que el schema directamente sin referenciar y que a nivel de esquema se tenga un ejemplo
    Esto lo que hara es recoger este ejemplo y crearlo en el apartado de componentes y luego referenciarlo , por ultimo se elimina el que tiene a nivel de esquema.
  version: 1.0.0
paths:
  /users:
    get:
      summary: Retrieves a list of users
      operationId: getUsers
      responses:
        '200':
          description: Successfully retrieved list of users
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          format: int64
                        name:
                          type: string
                        email:
                          type: string
                          format: email
                example:
                  users:
                    - id: 1
                      name: John Doe
                      email: john.doe@example.com
                    - id: 2
                      name: Jane Smith
                      email: jane.smith@example.com
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                example:
                  code: 500
                  message: Internal server error