openapi: 3.0.3
info:
  title: User API
  version: 1.0.0
paths:
  /user:
    get:
      summary: Retrieve user information
      responses:
        '200':
          description: User information retrieved successfully
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/UserBase'
                  - $ref: '#/components/schemas/UserStatus'
                  - $ref: '#/components/schemas/UserContact'
                  - $ref: '#/components/schemas/UserRoles'
components:
  schemas:
    UserBase:
      type: object
      properties:
        id:
          type: string
          example: "12345"
        name:
          type: string
          example: "John Doe"
    UserStatus:
      type: object
      properties:
        status:
          type: string
          example: "active"
        lastLogin:
          type: string
          format: date-time
          example: "2023-05-23T08:30:00Z"
    UserContact:
      type: object
      properties:
        email:
          type: string
          format: email
          example: "johndoe@example.com"
        phone:
          type: string
          example: "+1234567890"
    UserRoles:
      type: object
      properties:
        roles:
          type: array
          items:
            type: string
            example: "admin"
      example:  
        roles:
          - admin
          - user
