"use strict"

const _ = require("lodash");

module.exports = function() {
    return function createComponent (definition ,example , routeKey) {
        const nameComponent = `components.examples.${routeKey.split('.').pop()}.value`;
        _.set(definition ,  `${nameComponent.split('.').slice(0,-1).join('.')}.summary` , 'Example generated by script')
        if(!_.get(definition, nameComponent) && example){
          _.set(definition, nameComponent, example);
        }
        return `#/${nameComponent.split('.').slice(0, -1).join('/')}`
    }
}