"use strict"

const _ = require("lodash");


module.exports = function () {
  return function createComponent(definition, example, routeKey) {

    const routeComponent = `components.examples.${routeKey.split(".").pop()}`

    if (!_.get(definition, routeComponent) && example) {

      _.set( definition, `${routeComponent}.summary`, "Example generated by script");

      _.set(definition, `${routeComponent}.value`, example);
    }


    return `#/${routeComponent.split(".").join("/")}`
  };
};