"use strict"

const _ = require("lodash");
const verifyProperties = require('../utils/verifyProperties')()

module.exports = function() {
    return function trySetExample(definition, example, exampleKey, requiredProperties) {
        if (verifyProperties(example, requiredProperties) && !_.isEmpty(example)) {
          const name = createComponent(definition, example, exampleKey);
          _.set(definition, exampleKey, { $ref: name });
          require('../utils/sucess')(`Example generated for ${exampleKey}`)
          return true;
        }
        return false;
    }
}

const createComponent = (definition ,example , routeKey) => {
    const nameComponent = `components.examples.${routeKey.split('.').pop()}.value`;
    _.set(definition ,  `${nameComponent.split('.').slice(0,-1).join('.')}.summary` , 'Example generated by script')
    if(!_.get(definition, nameComponent) && example){
      _.set(definition, nameComponent, example);
    }
    return `#/${nameComponent.split('.').slice(0, -1).join('/')}`
}